import os
Import("environment libsapphireglextra")

source = [
	"opengl4_backend.c",
	"opengl4_context.c",
	"opengl4_image.c",
	"opengl4_shape.c",
	"opengl4_shader.c",
]

libs = [libsapphireglextra]

if os.name == "posix":
	libs += ["GL"]
elif os.name == "nt":
	libs += ["OpenGL32"]
	libs += ["GDI32", "user32", "winmm", "imm32", "ole32", "oleaut32"]

libopengl4sg = environment.StaticLibrary("opengl4sg", source, LIBS = libs)

Return("libopengl4sg")
