import os
Import("environment libsapphireglextra")

source = [
	"opengl_backend.c",
	"opengl_context.c",
	"opengl_image.c",
	"opengl_shape.c",
	"opengl_shader.c",
]

libs = [libsapphireglextra]

if os.name == "posix":
	libs += ["GL"]
elif os.name == "nt":
	libs += ["OpenGL32"]
	libs += ["GDI32", "user32", "winmm", "imm32", "ole32", "oleaut32"]

libopenglsg = environment.StaticLibrary("openglsg", source, LIBS = libs)

Return("libopenglsg")
