import os
Import("environment")

source = [
	"opengl_backend.c",
	"opengl_context.c",
	"opengl_image.c",
	"opengl_shape.c",
	"opengl_shader.c",
]

if os.name == "posix":
	libs = "GL"
else:
	libs = "OpenGL32"

libopenglsg = environment.StaticLibrary("openglsg", source, LIBS = libs)

Return("libopenglsg")
